/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zoinks360 (https://sketchfab.com/Zoinks360)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tennis-racket-0825c82b87644a16a4852a40528b8c01
title: Tennis Racket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Racket({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/racket/racket.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={0.4} position={[-1.2,0,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_4_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_handleNeck_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_handleRubber_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_11_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_28_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_9_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_shoulder_1_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.tennisRacket_Head_TennisRacket_GRP_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_17_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_27_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_24_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_7_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_handleBase_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_23_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_13_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_12_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_shoulder_2_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_20_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_29_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_2_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_19_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_5_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_14_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_18_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_1_tennisRacket_mesh_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_21_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_3_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_22_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_10_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_6_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_15_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_26_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_16_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_8_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.TennisRacket_GRP_tennisRacket_mesh_tennisRacket_mesh_25_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/racket/racket.glb')
